### ISSUE TITLE
incorrect url format

### ISSUE THREAD

**Issue by MahdiBaghbani** [cbeauhilton/cbeauhilton.github.io#1]
Hello there, I was just surfing forked repo's of Halve to see what new features people had added to it and I saw your website and found this:
[imgur image](https://imgur.com/a/fmGwMdb)
are you sure you are using correct url styling? two "/"s are after each other.
I didn't look into your codes because it's 2 AM and I'm too tired to do code review, but it might be a result of  a bad "href" linkage in your layouts.

**Comment by cbeauhilton** [comment]
Hey Mahdi - thank you for noticing that and sending in a note! I just saw this, hahaha. I was surprised to see an issue on my little blog. :)

It was a much simpler problem - when I defined my url in the _config.yaml file, I added a trailing `/`. Deleted it, and all is well.

Loving your fork of Halve, btw. I might nab that light/dark button. :)

**Comment by MahdiBaghbani** [comment]
:)
my forked halve repo is outdated, I develop the fork in a new repo at https://github.com/azadeh-afzar/Kianic-Jekyll-Theme
